---
title: "Tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(HW3)
```


Now we can display a simple example of how this package works. We are going to use linear model to predict the Miles per gallon based on horse power and weight of a car in mtcars data.

```{r cars}
data("mtcars")
X <- mtcars[, c("hp", "wt")]
y <- mtcars$mpg

#Construct a Multiple Linear Regression model to predict Miles per gallon based on horse power and weight of a car
model <- linear_model(X, y, intercept = TRUE)

#Now we can see the regression coefficients for each variable you use in the model
model$coefficients

#Also we can predict data based on acquired coefficients use lineaer_prediction function
head(linear_prediction(X,model$coefficients))

#There are also some useful functions to generate the result of regression 
result<-model_summary(model)

print(result)

```

You can compare these result with the original lm and summary function
```{r}
model2 <- lm(mpg~hp+wt, data = mtcars)
model2$coefficients
head(predict(model2,X))
summary(model2)
```

## This function can also work with other packages
```{r}
#install.packages("NHANES")
#install.packages("ggplot2")
library(NHANES)
library(ggplot2)
model3 <- linear_model(NHANES[,c("Weight","Height")],NHANES[,c("BPSysAve")])
# Assuming model3 contains fitted values and coefficients
fitted_values <- model3$fitted.values
coefficients <- model3$coefficients

# Prepare a data frame for plotting
plot_data <- data.frame(
  Weight = model3$model$X[,'Weight'],
  Height = model3$model$X[,'Height'],
  BPSysAve = model3$model$y,
  FittedBPSysAve = fitted_values
)

# Plot for Weight vs BPSysAve
ggplot(plot_data, aes(x = Weight, y = BPSysAve)) + 
  geom_point() + 
  geom_line(aes(y = FittedBPSysAve), color = "blue") +
  ggtitle("Weight v.s BPSysAve")

# Plot for Height vs BPSysAve
ggplot(plot_data, aes(x = Height, y = BPSysAve)) + 
  geom_point() + 
  geom_line(aes(y = FittedBPSysAve), color = "red") +
  ggtitle("Height v.s BPSysAve")

```

