#'Studnet-t test for the model generated by linear_model
#'
#'This function is designed to apply t-test to the result of fitted linear model coefficients
#'The corresponding t-test statistic is \eqn{t=\beta_j/SE(\beta_j)}
#'
#'@references
#'Wikipedia contributors. (n.d.). Student's t-test. In Wikipedia, The Free Encyclopedia. Retrieved [11/13/2023], from https://en.wikipedia.org/wiki/Student%27s_t-test
#'
#'@param model is the result of function linear_model()
#'
#'@return the list of Estimated value, standard error, t value, p-value of t-test for each coefficients
#'
#'@examples
#' # Load example dataset
#' data(mtcars)
#'
#' #Use horsepower&weight to predict miles per gallon
#' X <- mtcars[, c("hp", "wt")]  # horsepower and weight
#' y <- mtcars$mpg               # miles per gallon
#'
#' # Run the linear regression
#' model <- linear_model(X, y)
#' result <- parameter_t_test(model)
#'
#' print(result)
#'
#'@export

parameter_t_test <- function(model){
  if(model$intercept&!any(apply(model$model$X, 2, FUN = function(x) all(x == 1)))){
    X = cbind('(Intercept)'=1,model$model$X)
  }else{
    X = model$model$X
  }
  beta = model$coefficients
  ajj = diag(solve(t(X)%*%X))
  df = nrow(X)-model$rank
  mse = sum(model$residuals^2)/df
  std = sqrt(mse*ajj)
  t = 1/std*beta
  pvalue = 2*pt(abs(t),df,lower.tail = F)
  return(list(Estimate =beta,StdError=std, t_value=t, p_value=pvalue))
}
