#'Studnet-t test for the model generated by linear_model
#'
#'This function is designed to apply t-test to the result of fitted linear model coefficients
#'The corresponding t-test statistic is \eqn{t=\beta_j/SE(\beta_j)}
#'
#'@references
#'Wikipedia contributors. (n.d.). Student's t-test. In Wikipedia, The Free Encyclopedia. Retrieved [11/13/2023], from https://en.wikipedia.org/wiki/Student%27s_t-test
#'
#'@param model is the result of function linear_model()
#'
#'@return the list of Estimated value, standard error, t value, p-value of t-test for each coefficients
#'
#'@examples
#' # Load example dataset
#' data(mtcars)
#'
#' #Use horsepower&weight to predict miles per gallon
#' X <- mtcars[, c("hp", "wt")]  # horsepower and weight
#' y <- mtcars$mpg               # miles per gallon
#'
#' # Run the linear regression
#' model <- linear_model(X, y)
#' result <- parameter_t_test(model)
#'
#' print(result)
#'
#'@export

parameter_t_test <- function(model){

  if(model$intercept&!any(apply(model$model$X, 2, FUN = function(x) all(x == 1)))){
    X = cbind('(Intercept)'=1,model$model$X)
  }else{
    X = model$model$X
  }
  #t test
  beta = model$coefficients
  ajj = diag(solve(t(X)%*%X))
  df = nrow(X)-model$rank
  mse = sum(model$residuals^2)/df
  std = sqrt(mse*ajj)
  t = 1/std*beta
  ptvalue = 2*pt(abs(t),df,lower.tail = F)
  #F test
  SSY = sum((model$model$y-mean(model$model$y))^2)
  df1 = model$rank-1
  df2 = nrow(X)-model$rank
  f =(SSY - sum(model$residuals^2))/df1/(sum(model$residuals^2)/df2)
  pfvalue = pf(f, df1, df2,lower.tail = F)

  R2 = sum((fitted.values-mean(y))^2)/sum((y-mean(y))^2)
  R2_adj = 1-sum(residuals^2)/(nrow(X)-model$rank)/(sum((y-mean(y))^2)/(nrow(X)-1))

  return(list(Estimate =beta,StdError=std, t_value=t, pt_value=ptvalue, f_value=f, pf_value=pfvalue, R2 = R2, R2_adj = R2_adj))
}
